version: '3'
services:

  python:
    build:
      context: .
    env_file:
      - .env
    command: /bin/sh -c "taskiq scheduler tkq:sched && taskiq worker tkq:broker --fs-discover && python app.py"
