"""6

Revision ID: 0dd8615117ad
Revises: f2124db2aa98
Create Date: 2023-10-17 12:55:16.949566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd8615117ad'
down_revision: Union[str, None] = 'f2124db2aa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('malling_task_id_fkey', 'malling', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('malling_task_id_fkey', 'malling', 'taskiq_schedules', ['task_id'], ['id'])
    # ### end Alembic commands ###
