"""2

Revision ID: 7cbf79402062
Revises: 42cf286065cc
Create Date: 2023-10-17 11:07:37.299751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbf79402062'
down_revision: Union[str, None] = '42cf286065cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malling', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'malling', ['id'])
    op.create_unique_constraint(None, 'post_mailing', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'taskiq_schedules', ['id'])
    op.create_unique_constraint(None, 'urls', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'urls', type_='unique')
    op.drop_constraint(None, 'taskiq_schedules', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'post_mailing', type_='unique')
    op.drop_constraint(None, 'malling', type_='unique')
    op.drop_column('malling', 'is_sent')
    # ### end Alembic commands ###
