"""4

Revision ID: 9e4acbe6c78b
Revises: d67d977d55b0
Create Date: 2023-10-17 12:32:26.712262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4acbe6c78b'
down_revision: Union[str, None] = 'd67d977d55b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('malling', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'malling', 'taskiq_schedules', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'malling', type_='foreignkey')
    op.alter_column('malling', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
