"""1

Revision ID: cf7eda6a254e
Revises: 
Create Date: 2023-09-27 14:04:11.731085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7eda6a254e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_mailing', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('post_mailing_post_id_key', 'post_mailing', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_mailing_post_id_key', 'post_mailing', ['post_id'])
    op.alter_column('post_mailing', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
