"""3

Revision ID: d67d977d55b0
Revises: 7cbf79402062
Create Date: 2023-10-17 12:30:51.186587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67d977d55b0'
down_revision: Union[str, None] = '7cbf79402062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malling', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_column('malling', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malling', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('malling', 'task_id')
    # ### end Alembic commands ###
